name: rod_puzzle
version: 0.0.1
description: A starter template for a polymer.dart web app.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  core_elements: any
  polymer: '>=0.15.4 <0.16.0'
transformers:
- polymer:
    entry_points: web/index.html
- $dart2js:
    minify: true
